return {
	"Bekaboo/dropbar.nvim",
	enabled = true,
	event = "BufReadPost",
	opts = {
		icons = {
			enable = true,
			-- kinds = { ... },
			ui = {
				bar = {
					separator = "  ",
					extends = "…",
				},
				menu = {
					separator = " ",
					indicator = "  ",
				},
			},
		},
		-- symbol = { ... },
		-- bar = { ... },
		menu = {
			preview = true,
			hover = true,
			quick_navigation = true,
			entry = {
				padding = {
					left = 1,
					right = 1,
				},
			},
			scrollbar = {
				enable = true,
				background = false,
			},
			-- keymaps = { ... },
			win_configs = {
				style = "minimal",
				relative = "win",
			},
		},
		sources = {
			path = {
				max_depth = 16,
				preview = true,
				min_widths = {
					--,
				},
			},
			treesitter = {
				max_depth = 16,
				name_regex = [=[[#~!@\*&.]*[[:keyword:]]\+!\?]=]
					.. [=[\(\(\(->\)\+\|-\+\|\.\+\|:\+\|\s\+\)\?[#~!@\*&.]*[[:keyword:]]\+!\?\)*]=],
				valid_types = {
					"block_mapping_pair",
					"array",
					"boolean",
					"break_statement",
					"call",
					"case_statement",
					"class",
					"constant",
					"constructor",
					"continue_statement",
					"delete",
					"do_statement",
					"element",
					"enum",
					"enum_member",
					"event",
					"for_statement",
					"function",
					"goto_statement",
					"if_statement",
					"interface",
					"keyword",
					"macro",
					"method",
					"namespace",
					"null",
					"number",
					"operator",
					"package",
					"pair",
					"property",
					"reference",
					"repeat",
					"return_statement",
					"rule",
					"rule_set",
					"scope",
					"section",
					"specifier",
					"struct",
					"switch_statement",
					"table",
					"type",
					"type_parameter",
					"unit",
					"value",
					"variable",
					"while_statement",
					"declaration",
					"field",
					"identifier",
					"object",
					"statement",
				},
				min_widths = {
					--,
				},
			},
			lsp = {
				max_depth = 16,
				valid_symbols = {
					"File",
					"Module",
					"Namespace",
					"Package",
					"Class",
					"Method",
					"Property",
					"Field",
					"Constructor",
					"Enum",
					"Interface",
					"Function",
					"Variable",
					"Constant",
					"String",
					"Number",
					"Boolean",
					"Array",
					"Object",
					"Keyword",
					"Null",
					"EnumMember",
					"Struct",
					"Event",
					"Operator",
					"TypeParameter",
				},
				request = {
					ttl_init = 60,
					interval = 1000,
				},
				min_widths = {
					--,
				},
			},
			markdown = {
				max_depth = 6,
				parse = {
					look_ahead = 200,
				},
				min_widths = {
					--,
				},
			},
			terminal = {
				show_current = true,
			},
		},
		win_configs = {
			style = "minimal",
			border = "rounded",
		},
	},
}
