return {
	"catppuccin/nvim",
	name = "catppuccin",
	priority = 1000,
	opts = {
		flavour = "mocha",
		background = {
			light = "latte",
			dark = "mocha",
		},
		transparent_background = true,
		float = {
			transparent = true,
			solid = false,
		},
		show_end_of_buffer = false,
		term_colors = false,
		dim_inactive = {
			enabled = false,
			shade = "dark",
			percentage = 0.15,
		},
		no_italic = false,
		no_bold = false,
		no_underline = false,
		styles = {
			comments = {
				"italic",
			},
			conditionals = {
				"italic",
			},
			loops = {},
			functions = {},
			keywords = {},
			strings = {},
			variables = {},
			numbers = {},
			booleans = {},
			properties = {},
			types = {},
			operators = {},
			-- miscs = {},
		},
		lsp_styles = {
			virtual_text = {
				errors = {
					"italic",
				},
				hints = {
					"italic",
				},
				warnings = {
					"italic",
				},
				information = {
					"italic",
				},
				ok = {
					"italic",
				},
			},
			underlines = {
				errors = {
					"underline",
				},
				hints = {
					"underline",
				},
				warnings = {
					"underline",
				},
				information = {
					"underline",
				},
				ok = {
					"underline",
				},
			},
			inlay_hints = {
				background = true,
			},
		},
		color_overrides = {},
		custom_highlights = {},
		default_integrations = true,
		auto_integrations = true,
		integrations = {
			aerial = true,
			alpha = true,
			barbar = true,
			barbecue = {
				dim_dirname = true,
				bold_basename = true,
				dim_context = true,
				alt_background = true,
			},
			beacon = true,
			blink_cmp = {
				style = "bordered",
			},
			blink_indent = true,
			blink_pairs = true,
			buffon = true,
			cmp = true,
			coc_nvim = true,
			colorful_winsep = {
				enabled = true,
				color = "red",
			},
			copilot_vim = true,
			dadbod_ui = true,
			dap = true,
			dap_ui = true,
			dashboard = true,
			diffview = true,
			dropbar = {
				enabled = true,
				color_mode = true,
			},
			fern = true,
			fidget = true,
			flash = true,
			fzf = true,
			gitgraph = true,
			gitgutter = true,
			gitsigns = true,
			grug_far = true,
			harpoon = true,
			headlines = true,
			hop = true,
			illuminate = {
				enabled = true,
				lsp = true,
			},
			indent_blankline = {
				enabled = true,
				scope_color = "",
				colored_indent_levels = true,
			},
			leap = true,
			lightspeed = true,
			lir = {
				enabled = true,
				git_status = true,
			},
			lsp_saga = true,
			lsp_trouble = true,
			markview = true,
			mason = true,
			mini = {
				enabled = true,
				indentscope_color = "",
			},
			navic = {
				enabled = true,
				custom_bg = "NONE",
			},
			neotree = true,
			neogit = true,
			neotest = true,
			noice = true,
			notifier = true,
			notify = true,
			nvim_surround = true,
			nvimtree = true,
			octo = true,
			overseer = true,
			pounce = true,
			rainbow_delimiters = true,
			render_markdown = true,
			sandwich = true,
			signify = true,
			snacks = {
				enabled = true,
				indent_scope_color = "",
			},
			symbols_outline = true,
			telekasten = true,
			telescope = {
				enabled = true,
			},
			treesitter_context = true,
			ts_rainbow = true,
			ts_rainbow2 = true,
			ufo = true,
			vimwiki = true,
			vim_sneak = true,
			which_key = true,
			window_picker = true,
		},
	},
}
