return {
	"DrKJeff16/project.nvim",
	cmd = {
		"Project",
		"ProjectAdd",
		"ProjectConfig",
		"ProjectDelete",
		"ProjectExportJSON",
		"ProjectImportJSON",
		"ProjectHealth",
		"ProjectHistory",
		"ProjectRecents",
		"ProjectRoot",
		"ProjectSession",
	},
	dependencies = {
		"nvim-lua/plenary.nvim",
		"nvim-telescope/telescope.nvim",
		"ibhagwan/fzf-lua",
	},
	opts = {
		use_lsp = true,
		manual_mode = false,
		patterns = {
			"go.mod",
			".git",
			".github",
			"_darcs",
			".hg",
			".bzr",
			".svn",
			"Pipfile",
			"pyproject.toml",
			".pre-commit-config.yaml",
			".pre-commit-config.yml",
			".csproj",
			".sln",
			".nvim.lua",
		},
		allow_patterns_for_lsp = false,
		allow_different_owners = false,
		enable_autochdir = false,
		show_hidden = false,
		ignore_lsp = {
			--,
		},
		exclude_dirs = {
			--,
		},
		silent_chdir = true,
		scope_chdir = "global",
		datapath = vim.fn.stdpath("data"),
		historysize = 100,
		log = {
			enabled = false,
			max_size = 1.1,
			logpath = vim.fn.stdpath("state"),
		},
		fzf_lua = {
			enabled = false,
		},
		disable_on = {
			ft = {
				"",
				"NvimTree",
				"TelescopePrompt",
				"TelescopeResults",
				"alpha",
				"checkhealth",
				"lazy",
				"log",
				"ministarter",
				"neo-tree",
				"notify",
				"nvim-pack",
				"packer",
				"qf",
			},
			bt = {
				"help",
				"nofile",
				"nowrite",
				"terminal",
			},
		},
		telescope = {
			sort = "newest",
			prefer_file_browser = false,
			disable_file_picker = false,
			mappings = {
				n = {
					b = "browse_project_files",
					d = "delete_project",
					f = "find_project_files",
					r = "recent_project_files",
					s = "search_in_project_files",
					w = "change_working_directory",
				},
				i = {
					["<C-b>"] = "browse_project_files",
					["<C-d>"] = "delete_project",
					["<C-f>"] = "find_project_files",
					["<C-r>"] = "recent_project_files",
					["<C-s>"] = "search_in_project_files",
					["<C-w>"] = "change_working_directory",
				},
			},
		},
	},
}
